### ISSUE TITLE
"Shw All" Button doesn't show all dimension

### ISSUE THREAD

**Issue by orcavia** [kevancress/MeasureIt-ARCH#197]
![image](https://user-images.githubusercontent.com/68916685/140631217-186d8cea-7904-4897-aa35-ef6450917662.png)

**Comment by kevancress** [comment]
Hey @orcavia 

Not quite sure what the bug is in your screenshot. Leaving the Show All button enabled (like it is in your screenshot) will show all dimensions on all objects visible in the scene. Disabling the Show All button will only show dimensions for the currently selected object.

Please re-open this you're experiencing different behavior.

Also, It looks like your using an older version of the addon. If there is a bug, try using the latest development version.
