### ISSUE TITLE
Boolean Modifier breaks line sets

### ISSUE THREAD

**Issue by baldyman01** [kevancress/MeasureIt-ARCH#214]
I'm on the development version on 3.1.2 / Ubuntu 20.04

If I place a line set on a cube and then boolean through it, the line set vanishes from both viewport and render.

A Solidify modifier does not create the same problem. I use solidify and boolean regularly to create walls and punch out door holes. I tried checking the option  "Evaluate Depsgraph"  but this had no effect. 

To reproduce -
Create cube, remove top face and solidify
Apply solidify. Select top edges and add line group.
Lines appear as expected.
Add a boolean cuttter and cut into original cube.
Tab and tab again to enter/exit edit mode. 
Lines disappear.
![Screenshot from 2022-04-26 19-25-54](https://user-images.githubusercontent.com/33987743/165367492-90a4a11c-f302-458d-84c5-a940820c9c9f.png)

**Comment by kevancress** [comment]
Hey @baldyman01

Yeah this is a known issue, and one that, with the basic line group system, there's not really a solution for...

Basic line groups reference the mesh vertex indices, and some modifiers, like Boolean or Solidify, create new geometry and sometimes re-order or create new vertex indices when the object is evaluated in the dependency graph. 

The work around I've been using is the Dynamic Line Group feature I've added, this automatically adds lines to any edges with a crease sharper than a user specified value (and re-calculates when exiting edit mode, based on the evaluated mesh). I'm also working on a way to filter the output of this using vertex groups, since some of the generative modifiers, like solidify, can automatically populate vertex for you.

Here's a little demo video of how those features work in a setup similar to the one you've shown above:

https://user-images.githubusercontent.com/16860574/165883155-58a7d985-e1c4-4490-ba34-2bc078d43c39.mov

**Comment by baldyman01** [comment]
Thanks! I'll check it out.

**Comment by kevancress** [comment]
Hey @baldyman01 Closing this one for now, feel free to re-open if there's still issues!
