### ISSUE TITLE
Line weight not working (MacOS)

### ISSUE THREAD

**Issue by Blenderbugg** [kevancress/MeasureIt-ARCH#6]
In Object Mode - Line Weight - Edges not increasing only verts are showing as bigger. 
<img width="944" alt="Screen Shot 2019-03-27 at 7 10 51 am" src="https://user-images.githubusercontent.com/28837471/55030181-e5db9900-505f-11e9-95dd-0bd951e513a6.png">
<img width="922" alt="Screen Shot 2019-03-27 at 7 11 03 am" src="https://user-images.githubusercontent.com/28837471/55030182-e5db9900-505f-11e9-8345-3a3ab5b1252a.png">

**Comment by kevancress** [comment]
Did a little research, this looks like another difference between how Windows and MacOS support OpenGL line widths for drawing... look like the Blender devs have put some work into moving away from using OpenGL for this in the [source code](https://developer.blender.org/D3502?id=11321) I'll see if i can access these new draw calls from the add-on

**Comment by kevancress** [comment]
Last commit should fix this. I'm handling the line thickness with a geometry shader rather than using glLineWidth. The downside is that I still need to manually implement Anti-Aliasing in the shader, so for now lines will be a bit jagged. Let me know how the new version looks, there might still be some issues around corners

**Comment by kevancress** [comment]
Just brought back the Anti-Aliasing support so the jaggies should be fixed.

**Comment by Blenderbugg** [comment]
Looking good! The line weight numbers seem to make more sense. You don't seem to need to set a Z offset either.
