### ISSUE TITLE
Silhouette option missing in Scene and Object settings

### ISSUE THREAD

**Issue by c1symeon** [kevancress/MeasureIt-ARCH#62]
![image](https://user-images.githubusercontent.com/61176887/81810878-68f1d400-952c-11ea-9aef-bc5044b201fc.png)
![image](https://user-images.githubusercontent.com/61176887/81811139-d1d94c00-952c-11ea-92f6-59bed19f30f2.png)

**Comment by kevancress** [comment]
Hey! @c1symeon! Sorry I need to update the documentation on the silhouette features, since I've been changing how they function recently. Right now you can control the silhouette effect of a line through the lines 'z-offset' property, this gives more direct control over the types of silhouette lines being drawn, compared to the old toggle. It could probably use a more intuitive name than 'z-offset' though.

![silhouette via z-offset](https://user-images.githubusercontent.com/16860574/81834747-5fa63e80-950f-11ea-91a6-6c229eb5b58e.gif)
